/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtEmpleado;
import Controlador.CtlAvion;
import Modelo.ClsAvion;
import Modelo.ClsEmpleado;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mateo
 */
public class FrmAvion extends javax.swing.JFrame {

    ArrayList<ClsAvion> listaAvion = new ArrayList<ClsAvion>();
    ArrayList<ClsEmpleado> listaEmpleado = new ArrayList<ClsEmpleado>();
    CtEmpleado controladorEmpleado;
    CtlAvion controladorAvion;
    String nombre;
    public FrmAvion(){
        
    }

    public FrmAvion(String nombre) {
        initComponents();
        controladorAvion = new CtlAvion();
        controladorEmpleado = new CtEmpleado();
        this.nombre=nombre;
        try {
            listaAvion = controladorAvion.cargarArchivo(listaAvion);
            listaEmpleado = controladorEmpleado.cargarArchivo(listaEmpleado);
            listar();
            listarcomboxpiloto();
            listarcomboxazafata();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnElminar = new javax.swing.JButton();
        lblSerialAvion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAvion = new javax.swing.JTable();
        lblCapacidad = new javax.swing.JLabel();
        lblCodigoPiloto = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        lblCodigoAzafata = new javax.swing.JLabel();
        lblNombreAzafata = new javax.swing.JLabel();
        txtSerialAvion = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        JcbxCodigopiloto = new javax.swing.JComboBox<>();
        JcbxCodigoprimeraazafata = new javax.swing.JComboBox<>();
        JcbxCodigosegundaazafata = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Registrar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnElminar.setText("Eliminar");
        btnElminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElminarActionPerformed(evt);
            }
        });

        lblSerialAvion.setText("Serial Avion:");

        jTableAvion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Serial Avion", "Capacidad", "Codigo Piloto", "Nombre Piloto", "Codigo Azafata", "Nombre Azafata"
            }
        ));
        jScrollPane1.setViewportView(jTableAvion);

        lblCapacidad.setText("Capacidad:");

        lblCodigoPiloto.setText("Codigo Piloto:");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        lblCodigoAzafata.setText("Codigo Primera Azafata:");

        lblNombreAzafata.setText("Codigo Segunda Azafata:");

        txtSerialAvion.setEnabled(false);
        txtSerialAvion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerialAvionKeyTyped(evt);
            }
        });

        txtCapacidad.setEnabled(false);
        txtCapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadKeyTyped(evt);
            }
        });

        JcbxCodigopiloto.setEnabled(false);
        JcbxCodigopiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbxCodigopilotoActionPerformed(evt);
            }
        });

        JcbxCodigoprimeraazafata.setEnabled(false);
        JcbxCodigoprimeraazafata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbxCodigoprimeraazafataActionPerformed(evt);
            }
        });

        JcbxCodigosegundaazafata.setEnabled(false);
        JcbxCodigosegundaazafata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbxCodigosegundaazafataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegresar))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCodigoAzafata))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSerialAvion)
                            .addComponent(lblCapacidad)
                            .addComponent(lblCodigoPiloto)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNombreAzafata)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JcbxCodigopiloto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSerialAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addComponent(JcbxCodigosegundaazafata, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JcbxCodigoprimeraazafata, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(40, 40, 40)
                        .addComponent(btnModificar)
                        .addGap(49, 49, 49)
                        .addComponent(btnElminar)
                        .addGap(35, 35, 35)
                        .addComponent(btnNuevo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSerialAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSerialAvion))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCapacidad)
                            .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblCodigoPiloto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(JcbxCodigopiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoAzafata)
                            .addComponent(JcbxCodigoprimeraazafata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addComponent(btnModificar)
                            .addComponent(btnElminar)
                            .addComponent(btnNuevo))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAzafata)
                    .addComponent(JcbxCodigosegundaazafata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmAdministrador administrador = new FrmAdministrador(nombre);
        administrador.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        String serial = txtSerialAvion.getText();
        int capacidad = Integer.parseInt(txtCapacidad.getText());
        String codigoPiloto = JcbxCodigopiloto.getSelectedItem().toString();
        String codigoPrimeraAzafata = JcbxCodigoprimeraazafata.getSelectedItem().toString();
        String codigoSegundaAzafata = JcbxCodigosegundaazafata.getSelectedItem().toString();
        listaAvion = listaAvion = controladorAvion.registrarAvion(listaAvion, serial, capacidad, codigoPiloto, codigoPrimeraAzafata, codigoSegundaAzafata);
        String res = controladorAvion.guardarArchivo(listaAvion);
        listar();
        limpiar();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String serial = JOptionPane.showInputDialog("Ingrese el serial del avion que desea buscar");
        txtSerialAvion.setEnabled(false);
        ClsAvion avion = null;
        avion = controladorAvion.buscarAvion(listaAvion, serial);
        if (avion == null) {
            limpiar();
        } else {
            txtSerialAvion.setText(avion.getSerial());
            txtCapacidad.setText(avion.getCapacidad() + "");
            JcbxCodigopiloto.setSelectedItem(avion.getCodigoPiloto());
            JcbxCodigoprimeraazafata.setSelectedItem(avion.getCodigoPrimeraazafata());
            JcbxCodigosegundaazafata.setSelectedItem(avion.getCodigoSegundaazafata());

        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        String serial = txtSerialAvion.getText();
        int capacidad = Integer.parseInt(txtCapacidad.getText());
        String codigoPiloto = JcbxCodigopiloto.getSelectedItem().toString();
        String codigoPrimeraAzafata = JcbxCodigoprimeraazafata.getSelectedItem().toString();
        String codigoSegundaAzafata = JcbxCodigosegundaazafata.getSelectedItem().toString();
        listaAvion = controladorAvion.modificarAvion(listaAvion, serial, capacidad, codigoPiloto, codigoPrimeraAzafata, codigoSegundaAzafata);
        String res = controladorAvion.guardarArchivo(listaAvion);
        listar();
        limpiar();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnElminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElminarActionPerformed
        String serial = JOptionPane.showInputDialog("ingrese el serial del avion que desea eliminar");
        listaAvion = controladorAvion.EliminarAvion(listaAvion, serial);
        String res = controladorAvion.guardarArchivo(listaAvion);
        listar();
    }//GEN-LAST:event_btnElminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        txtSerialAvion.setEnabled(true);
        txtCapacidad.setEnabled(true);
        JcbxCodigopiloto.setEnabled(true);
        JcbxCodigoprimeraazafata.setEnabled(true);
        JcbxCodigosegundaazafata.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(true);
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtSerialAvionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialAvionKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtSerialAvionKeyTyped

    private void txtCapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadKeyTyped

        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCapacidadKeyTyped

    private void JcbxCodigopilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbxCodigopilotoActionPerformed
        listarcomboxpiloto();
    }//GEN-LAST:event_JcbxCodigopilotoActionPerformed

    private void JcbxCodigoprimeraazafataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbxCodigoprimeraazafataActionPerformed
        listarcomboxazafata();
    }//GEN-LAST:event_JcbxCodigoprimeraazafataActionPerformed

    private void JcbxCodigosegundaazafataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbxCodigosegundaazafataActionPerformed
        listarcomboxazafata();
    }//GEN-LAST:event_JcbxCodigosegundaazafataActionPerformed
    public void limpiar() {

        txtSerialAvion.setText("");
        txtCapacidad.setText("");
        JcbxCodigopiloto.setSelectedItem("");
        JcbxCodigoprimeraazafata.setSelectedItem("");
        JcbxCodigosegundaazafata.setSelectedItem("");

    }

    public void listar() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = controladorAvion.listarElementos(listaAvion);
        jTableAvion.setModel(modelo);

    }

    private void listarcomboxpiloto() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < listaEmpleado.size(); i++) {
            if (listaEmpleado.get(i).getCargo().equals("Piloto")) {
                modelo.addElement(listaEmpleado.get(i).getCedula() + " " + listaEmpleado.get(i).getNombre());
            }
            JcbxCodigopiloto.setModel(modelo);
        }
    }

    private void listarcomboxazafata() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < listaEmpleado.size(); i++) {
            if (listaEmpleado.get(i).getCargo().equals("Azafata")) {
                modelo.addElement(listaEmpleado.get(i).getCedula() + " " + listaEmpleado.get(i).getNombre());
            }
            JcbxCodigoprimeraazafata.setModel(modelo);
            JcbxCodigosegundaazafata.setModel(modelo);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAvion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbxCodigopiloto;
    private javax.swing.JComboBox<String> JcbxCodigoprimeraazafata;
    private javax.swing.JComboBox<String> JcbxCodigosegundaazafata;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnElminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAvion;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblCodigoAzafata;
    private javax.swing.JLabel lblCodigoPiloto;
    private javax.swing.JLabel lblNombreAzafata;
    private javax.swing.JLabel lblSerialAvion;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtSerialAvion;
    // End of variables declaration//GEN-END:variables
}
