/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtPromocion;
import Controlador.CtPromocion;
import Modelo.ClsPromocion;
import Modelo.ClsRuta;
import Modelo.ClsSillas;
import Modelo.ClsVuelo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Javier Parra
 */
public class FrmEquipaje extends javax.swing.JFrame {

    ArrayList<ClsPromocion> listapromocion = new ArrayList<ClsPromocion>();
    ArrayList<ClsVuelo>listavuelos= new ArrayList<ClsVuelo>();
    CtPromocion controladorPromocion;
    String nombreCliente;
    String cedulaCliente;
    int pasajero;
    ClsVuelo vuelo;
    ArrayList<String> silla = new ArrayList<String>();

    public FrmEquipaje() {
        initComponents();
    }

    public FrmEquipaje(ArrayList<ClsVuelo>listavuelo,ArrayList<String> sillas,ClsVuelo vuelo, String nombre, String cedula,int pasajeros) {
        this.nombreCliente = nombre;
        this.cedulaCliente = cedula;
        this.silla = sillas;
        this.vuelo=vuelo;
        this.pasajero=pasajeros;
        this.listavuelos=listavuelo;
        initComponents();
        controladorPromocion = new CtPromocion();
        try {
            listapromocion = controladorPromocion.cargarArchivo(listapromocion);
            listar();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void listar() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = listarOferta(listapromocion);
        jTableEquipaje.setModel(modelo);
    }

    public DefaultTableModel listarOferta(ArrayList<ClsPromocion> listaPromocion) {
        DefaultTableModel modelo;
        String nombreColumnas[] = {"Fecha", "Nombre promocion", "Equipaje", "Millas", "Valor Promocion"};
        modelo = new DefaultTableModel(new Object[][]{}, nombreColumnas);
        try {
            for (int i = 0; i < listaPromocion.size(); i++) {
                modelo.addRow(new Object[]{listaPromocion.get(i).getFecha(), listaPromocion.get(i).getNombrePromocion(), listaPromocion.get(i).getEquipaje(), listaPromocion.get(i).getMillas(), listaPromocion.get(i).getValorPromocion()});
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        return modelo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEquipaje = new javax.swing.JTable();
        btnAdquirirPromocion = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableEquipaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Nombre Promocion ", "Equipaje", "Millas", "Valor Promocion "
            }
        ));
        jScrollPane1.setViewportView(jTableEquipaje);

        btnAdquirirPromocion.setText("Adquirir");
        btnAdquirirPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdquirirPromocionActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdquirirPromocion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdquirirPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmSillas sillas = new FrmSillas(listavuelos, vuelo, nombreCliente, cedulaCliente,pasajero);
        sillas.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAdquirirPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdquirirPromocionActionPerformed
        String nombrepromocion = JOptionPane.showInputDialog("ingrese nombre de la promocion");
       ClsPromocion promocion;
        for (int i = 0; i < listapromocion.size(); i++) {
            if (nombrepromocion.equals(listapromocion.get(i).getNombrePromocion())) {
                FrmIngresarDatos datos = new FrmIngresarDatos(listavuelos,silla,vuelo, nombreCliente, cedulaCliente, nombrepromocion);
                datos.setVisible(true);
                dispose();
                break;
            } else {
                JOptionPane.showMessageDialog(this, "Promocion no existe");
                break;
            }

        }


    }//GEN-LAST:event_btnAdquirirPromocionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEquipaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEquipaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEquipaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEquipaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEquipaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdquirirPromocion;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEquipaje;
    // End of variables declaration//GEN-END:variables
}
