/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtAdministrador;
import Controlador.CtCliente;
import Controlador.CtEmpleado;
import Controlador.CtLogin;
import Modelo.ClsAdministrador;
import Modelo.ClsCliente;
import Modelo.ClsEmpleado;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mateo
 */
public class FrmLogin extends javax.swing.JFrame {

    ClsAdministrador administrado;
    ArrayList<ClsEmpleado> listaEmpleado;
    ArrayList<ClsCliente> listaCliente;
    CtEmpleado controladorEmpleado;
    CtCliente controladorCliente;
    CtLogin controladorLogin;
    CtAdministrador administrar;

    public FrmLogin() {
        initComponents();
        controladorEmpleado = new CtEmpleado();
        controladorLogin = new CtLogin();
        controladorCliente = new CtCliente();
        administrado = new ClsAdministrador();
        listaCliente = new ArrayList<ClsCliente>();
        listaEmpleado = new ArrayList<ClsEmpleado>();
        administrar = new CtAdministrador();
        try {
            listaEmpleado = controladorEmpleado.cargarArchivo(listaEmpleado);
            listaCliente = controladorCliente.cargarArchivo(listaCliente);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblPassword = new javax.swing.JLabel();
        JpasswordContrasena = new javax.swing.JPasswordField();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblPregunta = new javax.swing.JLabel();
        JrbtnAdministrador = new javax.swing.JRadioButton();
        JrbtnCliente = new javax.swing.JRadioButton();
        JrbtnEmpleado = new javax.swing.JRadioButton();
        BtnIngresar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmGestionar = new javax.swing.JMenu();
        JmtGestionarCliente = new javax.swing.JMenuItem();
        JmOpciones = new javax.swing.JMenu();
        JtmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPassword.setText("Password");

        JpasswordContrasena.setEnabled(false);

        lblCedula.setText("Cedula");

        txtCedula.setEnabled(false);

        lblPregunta.setBackground(new java.awt.Color(255, 255, 255));
        lblPregunta.setText("Desea ingresar a :");

        buttonGroup1.add(JrbtnAdministrador);
        JrbtnAdministrador.setText("Administrador");
        JrbtnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbtnAdministradorActionPerformed(evt);
            }
        });

        buttonGroup1.add(JrbtnCliente);
        JrbtnCliente.setText("Cliente");
        JrbtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbtnClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(JrbtnEmpleado);
        JrbtnEmpleado.setText("Empleado");
        JrbtnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbtnEmpleadoActionPerformed(evt);
            }
        });

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Bienvenidos");

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        JmGestionar.setText("Registro");

        JmtGestionarCliente.setText("Cliente");
        JmtGestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmtGestionarClienteActionPerformed(evt);
            }
        });
        JmGestionar.add(JmtGestionarCliente);

        jMenuBar1.add(JmGestionar);

        JmOpciones.setText("Opciones");

        JtmSalir.setText("Salir");
        JtmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtmSalirActionPerformed(evt);
            }
        });
        JmOpciones.add(JtmSalir);

        jMenuBar1.add(JmOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblPregunta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblCedula))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JrbtnAdministrador)
                    .addComponent(JrbtnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JrbtnEmpleado)
                    .addComponent(JpasswordContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(BtnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(JrbtnEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JrbtnCliente)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JrbtnAdministrador)
                    .addComponent(lblPregunta))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(JpasswordContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIngresar)
                    .addComponent(BtnSalir))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JmtGestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmtGestionarClienteActionPerformed
        FrmregistrarCliente registrocliente = new FrmregistrarCliente();
        registrocliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_JmtGestionarClienteActionPerformed

    private void JtmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtmSalirActionPerformed
        dispose();
    }//GEN-LAST:event_JtmSalirActionPerformed

    private void JrbtnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbtnAdministradorActionPerformed
        BtnIngresar.setEnabled(true);
        txtCedula.setEnabled(true);
        JpasswordContrasena.setEnabled(true);
        limpiar();
    }//GEN-LAST:event_JrbtnAdministradorActionPerformed

    private void JrbtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbtnClienteActionPerformed
        BtnIngresar.setEnabled(true);
        txtCedula.setEnabled(true);
        JpasswordContrasena.setEnabled(true);
        limpiar();
    }//GEN-LAST:event_JrbtnClienteActionPerformed

    private void JrbtnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbtnEmpleadoActionPerformed
        BtnIngresar.setEnabled(true);
        txtCedula.setEnabled(true);
        JpasswordContrasena.setEnabled(true);
        limpiar();

    }//GEN-LAST:event_JrbtnEmpleadoActionPerformed

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        if (JrbtnEmpleado.isSelected() == true) {
            String cedula = txtCedula.getText();
            String password = JpasswordContrasena.getText();
            String empleado = JrbtnEmpleado.getText();
            String respuesta = controladorLogin.Login(listaEmpleado, listaCliente, administrado, empleado, cedula, password);
            if (respuesta.equals("Si")) {
                FrmmenuEmpleado menuempleado = new FrmmenuEmpleado();
                menuempleado.setVisible(true);
                dispose();
            } else {
                if (respuesta.equals("No")) {
                    JOptionPane.showMessageDialog(null, "cedula o password incorrecto");
                    limpiar();
                }
            }
        }
        if (JrbtnCliente.isSelected() == true) {
            String cedula = txtCedula.getText();
            String password = JpasswordContrasena.getText();
            String cliente = JrbtnCliente.getText();
            String respuesta = controladorLogin.Login(listaEmpleado, listaCliente, administrado, cliente, cedula, password);
            if (respuesta.equals("Si")) {
                String nombre = controladorCliente.buscarCedula(cedula, listaCliente);

                FrmmenuCliente menucliente = new FrmmenuCliente(nombre);
                menucliente.setVisible(true);
                dispose();
            } else {
                if (respuesta.equals("No")) {
                    JOptionPane.showMessageDialog(null, "cedula o password incorrecto");
                    limpiar();
                }
            }

        }
        if (JrbtnAdministrador.isSelected() == true) {
            String cedula = txtCedula.getText();
            String password = JpasswordContrasena.getText();
            String administrador = JrbtnAdministrador.getText();
            String respuesta = controladorLogin.Login(listaEmpleado, listaCliente, administrado, administrador, cedula, password);
            if (respuesta.equals("Si")) {
                String nombre = administrar.buscarCedula(cedula, administrado);
                FrmAdministrador administradores = new FrmAdministrador(nombre);
                administradores.setVisible(true);
                dispose();
            } else {
                if (respuesta.equals("No")) {
                    JOptionPane.showMessageDialog(null, "cedula o password incorrecto");
                    limpiar();
                }
            }

        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed
    public void limpiar() {
        txtCedula.setText("");
        JpasswordContrasena.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JMenu JmGestionar;
    private javax.swing.JMenu JmOpciones;
    private javax.swing.JMenuItem JmtGestionarCliente;
    private javax.swing.JPasswordField JpasswordContrasena;
    private javax.swing.JRadioButton JrbtnAdministrador;
    private javax.swing.JRadioButton JrbtnCliente;
    private javax.swing.JRadioButton JrbtnEmpleado;
    private javax.swing.JMenuItem JtmSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
