/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author mateo
 */
public class FrmPuestosprueba extends javax.swing.JFrame {

    public FrmPuestosprueba() {
        initComponents();
    }


/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Jrbtnpuesto46 = new javax.swing.JRadioButton();
        Jrbtnpuesto47 = new javax.swing.JRadioButton();
        Jrbtnpuesto48 = new javax.swing.JRadioButton();
        Jrbtnpuesto49 = new javax.swing.JRadioButton();
        Jrbtnpuesto6 = new javax.swing.JRadioButton();
        Jrbtnpuesto50 = new javax.swing.JRadioButton();
        Jrbtnpuesto7 = new javax.swing.JRadioButton();
        Jrbtnpuesto51 = new javax.swing.JRadioButton();
        Jrbtnpuesto8 = new javax.swing.JRadioButton();
        Jrbtnpuesto52 = new javax.swing.JRadioButton();
        Jrbtnpuesto9 = new javax.swing.JRadioButton();
        Jrbtnpuesto53 = new javax.swing.JRadioButton();
        Jrbtnpuesto10 = new javax.swing.JRadioButton();
        Jrbtnpuesto54 = new javax.swing.JRadioButton();
        Jrbtnpuesto11 = new javax.swing.JRadioButton();
        Jrbtnpuesto55 = new javax.swing.JRadioButton();
        Jrbtnpuesto12 = new javax.swing.JRadioButton();
        Jrbtnpuesto13 = new javax.swing.JRadioButton();
        Jrbtnpuesto14 = new javax.swing.JRadioButton();
        Jrbtnpuesto15 = new javax.swing.JRadioButton();
        Jrbtnpuesto16 = new javax.swing.JRadioButton();
        Jrbtnpuesto17 = new javax.swing.JRadioButton();
        Jrbtnpuesto18 = new javax.swing.JRadioButton();
        Jrbtnpuesto19 = new javax.swing.JRadioButton();
        Jrbtnpuesto20 = new javax.swing.JRadioButton();
        Jrbtnpuesto21 = new javax.swing.JRadioButton();
        Jrbtnpuesto22 = new javax.swing.JRadioButton();
        Jrbtnpuesto23 = new javax.swing.JRadioButton();
        Jrbtnpuesto56 = new javax.swing.JRadioButton();
        Jrbtnpuesto24 = new javax.swing.JRadioButton();
        Jrbtnpuesto57 = new javax.swing.JRadioButton();
        Jrbtnpuesto25 = new javax.swing.JRadioButton();
        Jrbtnpuesto58 = new javax.swing.JRadioButton();
        Jrbtnpuesto59 = new javax.swing.JRadioButton();
        Jrbtnpuesto60 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Jrbtnpuesto26 = new javax.swing.JRadioButton();
        Jrbtnpuesto27 = new javax.swing.JRadioButton();
        Jrbtnpuesto28 = new javax.swing.JRadioButton();
        Jrbtnpuesto29 = new javax.swing.JRadioButton();
        Jrbtnpuesto30 = new javax.swing.JRadioButton();
        Jrbtnpuesto31 = new javax.swing.JRadioButton();
        Jrbtnpuesto32 = new javax.swing.JRadioButton();
        Jrbtnpuesto33 = new javax.swing.JRadioButton();
        Jrbtnpuesto34 = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        Jrbtnpuesto35 = new javax.swing.JRadioButton();
        Jrbtnpuesto36 = new javax.swing.JRadioButton();
        Jrbtnpuesto37 = new javax.swing.JRadioButton();
        Jrbtnpuesto38 = new javax.swing.JRadioButton();
        Jrbtnpuesto39 = new javax.swing.JRadioButton();
        Jrbtnpuesto40 = new javax.swing.JRadioButton();
        Jrbtnpuesto41 = new javax.swing.JRadioButton();
        Jrbtnpuesto42 = new javax.swing.JRadioButton();
        Jrbtnpuesto43 = new javax.swing.JRadioButton();
        Jrbtnpuesto44 = new javax.swing.JRadioButton();
        Jrbtnpuesto1 = new javax.swing.JRadioButton();
        Jrbtnpuesto45 = new javax.swing.JRadioButton();
        Jrbtnpuesto2 = new javax.swing.JRadioButton();
        Jrbtnpuesto3 = new javax.swing.JRadioButton();
        Jrbtnpuesto4 = new javax.swing.JRadioButton();
        Jrbtnpuesto5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jrbtnpuesto46.setText("Puesto 46");

        Jrbtnpuesto47.setText("Puesto 47");

        Jrbtnpuesto48.setText("Puesto 48");

        Jrbtnpuesto49.setText("Puesto 49");

        Jrbtnpuesto6.setText("Puesto 6");

        Jrbtnpuesto50.setText("Puesto 50");

        Jrbtnpuesto7.setText("Puesto 7");

        Jrbtnpuesto51.setText("Puesto 51");

        Jrbtnpuesto8.setText("Puesto 8");

        Jrbtnpuesto52.setText("Puesto 52");

        Jrbtnpuesto9.setText("Puesto 9");

        Jrbtnpuesto53.setText("Puesto 53");

        Jrbtnpuesto10.setText("Puesto 10");

        Jrbtnpuesto54.setText("Puesto 54");

        Jrbtnpuesto11.setText("Puesto 11");

        Jrbtnpuesto55.setText("Puesto 55");

        Jrbtnpuesto12.setText("Puesto 12");
        Jrbtnpuesto12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jrbtnpuesto12ActionPerformed(evt);
            }
        });

        Jrbtnpuesto13.setText("Puesto 13");

        Jrbtnpuesto14.setText("Puesto 14");

        Jrbtnpuesto15.setText("Puesto 15");

        Jrbtnpuesto16.setText("Puesto 16");

        Jrbtnpuesto17.setText("Puesto 17");

        Jrbtnpuesto18.setText("Puesto 18");

        Jrbtnpuesto19.setText("Puesto 19");
        Jrbtnpuesto19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jrbtnpuesto19ActionPerformed(evt);
            }
        });

        Jrbtnpuesto20.setText("Puesto 20");

        Jrbtnpuesto21.setText("Puesto 21");

        Jrbtnpuesto22.setText("Puesto 22");

        Jrbtnpuesto23.setText("Puesto 23");

        Jrbtnpuesto56.setText("Puesto 56");

        Jrbtnpuesto24.setText("Puesto 24");

        Jrbtnpuesto57.setText("Puesto 57");

        Jrbtnpuesto25.setText("Puesto 25");

        Jrbtnpuesto58.setText("Puesto 58");

        Jrbtnpuesto59.setText("Puesto 59");

        Jrbtnpuesto60.setText("Puesto 60");

        jLabel1.setText("Economica");

        jLabel2.setText("Intermedio");

        Jrbtnpuesto26.setText("Puesto 26");

        Jrbtnpuesto27.setText("Puesto 27");

        Jrbtnpuesto28.setText("Puesto 28");

        Jrbtnpuesto29.setText("Puesto 29");

        Jrbtnpuesto30.setText("Puesto 30");

        Jrbtnpuesto31.setText("Puesto 31");

        Jrbtnpuesto32.setText("Puesto 32");

        Jrbtnpuesto33.setText("Puesto 33");

        Jrbtnpuesto34.setText("Puesto 34");

        Jrbtnpuesto35.setText("Puesto 35");

        Jrbtnpuesto36.setText("Puesto 36");
        Jrbtnpuesto36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jrbtnpuesto36ActionPerformed(evt);
            }
        });

        Jrbtnpuesto37.setText("Puesto 37");

        Jrbtnpuesto38.setText("Puesto 38");

        Jrbtnpuesto39.setText("Puesto 39");

        Jrbtnpuesto40.setText("Puesto 40");

        Jrbtnpuesto41.setText("Puesto 41");

        Jrbtnpuesto42.setText("Puesto 42");

        Jrbtnpuesto43.setText("Puesto 43");

        Jrbtnpuesto44.setText("Puesto 44");

        Jrbtnpuesto1.setText("Puesto 1");
        Jrbtnpuesto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jrbtnpuesto1ActionPerformed(evt);
            }
        });

        Jrbtnpuesto45.setText("Puesto 45");

        Jrbtnpuesto2.setText("Puesto 2");
        Jrbtnpuesto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jrbtnpuesto2ActionPerformed(evt);
            }
        });

        Jrbtnpuesto3.setText("Puesto 3");

        Jrbtnpuesto4.setText("Puesto 4");

        Jrbtnpuesto5.setText("Puesto 5");

        jLabel3.setText("VIP");

        jDesktopPane1.setLayer(Jrbtnpuesto46, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto47, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto48, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto49, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto50, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto51, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto52, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto53, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto54, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto55, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto56, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto57, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto58, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto59, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto60, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto43, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto44, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto45, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Jrbtnpuesto5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Jrbtnpuesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Jrbtnpuesto7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto13, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                    .addGap(10, 10, 10)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Jrbtnpuesto8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto14, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Jrbtnpuesto31, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Jrbtnpuesto26, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Jrbtnpuesto49, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto37, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto43, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Jrbtnpuesto38, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(10, 10, 10)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jrbtnpuesto21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jrbtnpuesto27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jrbtnpuesto33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jrbtnpuesto39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jrbtnpuesto45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jrbtnpuesto51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jrbtnpuesto57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jrbtnpuesto3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jrbtnpuesto9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jrbtnpuesto15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Jrbtnpuesto4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto10, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Jrbtnpuesto5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto11, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Jrbtnpuesto18, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jrbtnpuesto6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Jrbtnpuesto34, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                            .addComponent(Jrbtnpuesto35, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Jrbtnpuesto36, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(Jrbtnpuesto29, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                                .addComponent(Jrbtnpuesto23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(16, 16, 16)
                                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Jrbtnpuesto24, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                                .addComponent(Jrbtnpuesto30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Jrbtnpuesto58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto46, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Jrbtnpuesto41, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Jrbtnpuesto42, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jrbtnpuesto60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(46, 46, 46))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(3, 3, 3)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrbtnpuesto1)
                    .addComponent(Jrbtnpuesto2)
                    .addComponent(Jrbtnpuesto3)
                    .addComponent(Jrbtnpuesto4)
                    .addComponent(Jrbtnpuesto5)
                    .addComponent(Jrbtnpuesto6))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrbtnpuesto7)
                    .addComponent(Jrbtnpuesto8)
                    .addComponent(Jrbtnpuesto9)
                    .addComponent(Jrbtnpuesto10)
                    .addComponent(Jrbtnpuesto11)
                    .addComponent(Jrbtnpuesto12))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrbtnpuesto13)
                    .addComponent(Jrbtnpuesto15)
                    .addComponent(Jrbtnpuesto14)
                    .addComponent(Jrbtnpuesto16)
                    .addComponent(Jrbtnpuesto17)
                    .addComponent(Jrbtnpuesto18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrbtnpuesto19)
                    .addComponent(Jrbtnpuesto20)
                    .addComponent(Jrbtnpuesto21)
                    .addComponent(Jrbtnpuesto22)
                    .addComponent(Jrbtnpuesto23)
                    .addComponent(Jrbtnpuesto24))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jrbtnpuesto30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Jrbtnpuesto25)
                        .addComponent(Jrbtnpuesto26)
                        .addComponent(Jrbtnpuesto27)
                        .addComponent(Jrbtnpuesto28)
                        .addComponent(Jrbtnpuesto29)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrbtnpuesto31)
                    .addComponent(Jrbtnpuesto32)
                    .addComponent(Jrbtnpuesto33)
                    .addComponent(Jrbtnpuesto34)
                    .addComponent(Jrbtnpuesto35)
                    .addComponent(Jrbtnpuesto36))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrbtnpuesto37)
                    .addComponent(Jrbtnpuesto38)
                    .addComponent(Jrbtnpuesto39)
                    .addComponent(Jrbtnpuesto40)
                    .addComponent(Jrbtnpuesto41)
                    .addComponent(Jrbtnpuesto42))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrbtnpuesto43)
                    .addComponent(Jrbtnpuesto44)
                    .addComponent(Jrbtnpuesto45)
                    .addComponent(Jrbtnpuesto46)
                    .addComponent(Jrbtnpuesto47)
                    .addComponent(Jrbtnpuesto48))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrbtnpuesto49)
                    .addComponent(Jrbtnpuesto50)
                    .addComponent(Jrbtnpuesto51)
                    .addComponent(Jrbtnpuesto52)
                    .addComponent(Jrbtnpuesto53)
                    .addComponent(Jrbtnpuesto54))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrbtnpuesto55)
                    .addComponent(Jrbtnpuesto56)
                    .addComponent(Jrbtnpuesto57)
                    .addComponent(Jrbtnpuesto58)
                    .addComponent(Jrbtnpuesto59)
                    .addComponent(Jrbtnpuesto60))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jrbtnpuesto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jrbtnpuesto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jrbtnpuesto1ActionPerformed

    private void Jrbtnpuesto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jrbtnpuesto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jrbtnpuesto2ActionPerformed

    private void Jrbtnpuesto19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jrbtnpuesto19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jrbtnpuesto19ActionPerformed

    private void Jrbtnpuesto36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jrbtnpuesto36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jrbtnpuesto36ActionPerformed

    private void Jrbtnpuesto12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jrbtnpuesto12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jrbtnpuesto12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPuestosprueba.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPuestosprueba.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPuestosprueba.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPuestosprueba.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPuestosprueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Jrbtnpuesto1;
    private javax.swing.JRadioButton Jrbtnpuesto10;
    private javax.swing.JRadioButton Jrbtnpuesto11;
    private javax.swing.JRadioButton Jrbtnpuesto12;
    private javax.swing.JRadioButton Jrbtnpuesto13;
    private javax.swing.JRadioButton Jrbtnpuesto14;
    private javax.swing.JRadioButton Jrbtnpuesto15;
    private javax.swing.JRadioButton Jrbtnpuesto16;
    private javax.swing.JRadioButton Jrbtnpuesto17;
    private javax.swing.JRadioButton Jrbtnpuesto18;
    private javax.swing.JRadioButton Jrbtnpuesto19;
    private javax.swing.JRadioButton Jrbtnpuesto2;
    private javax.swing.JRadioButton Jrbtnpuesto20;
    private javax.swing.JRadioButton Jrbtnpuesto21;
    private javax.swing.JRadioButton Jrbtnpuesto22;
    private javax.swing.JRadioButton Jrbtnpuesto23;
    private javax.swing.JRadioButton Jrbtnpuesto24;
    private javax.swing.JRadioButton Jrbtnpuesto25;
    private javax.swing.JRadioButton Jrbtnpuesto26;
    private javax.swing.JRadioButton Jrbtnpuesto27;
    private javax.swing.JRadioButton Jrbtnpuesto28;
    private javax.swing.JRadioButton Jrbtnpuesto29;
    private javax.swing.JRadioButton Jrbtnpuesto3;
    private javax.swing.JRadioButton Jrbtnpuesto30;
    private javax.swing.JRadioButton Jrbtnpuesto31;
    private javax.swing.JRadioButton Jrbtnpuesto32;
    private javax.swing.JRadioButton Jrbtnpuesto33;
    private javax.swing.JRadioButton Jrbtnpuesto34;
    private javax.swing.JRadioButton Jrbtnpuesto35;
    private javax.swing.JRadioButton Jrbtnpuesto36;
    private javax.swing.JRadioButton Jrbtnpuesto37;
    private javax.swing.JRadioButton Jrbtnpuesto38;
    private javax.swing.JRadioButton Jrbtnpuesto39;
    private javax.swing.JRadioButton Jrbtnpuesto4;
    private javax.swing.JRadioButton Jrbtnpuesto40;
    private javax.swing.JRadioButton Jrbtnpuesto41;
    private javax.swing.JRadioButton Jrbtnpuesto42;
    private javax.swing.JRadioButton Jrbtnpuesto43;
    private javax.swing.JRadioButton Jrbtnpuesto44;
    private javax.swing.JRadioButton Jrbtnpuesto45;
    private javax.swing.JRadioButton Jrbtnpuesto46;
    private javax.swing.JRadioButton Jrbtnpuesto47;
    private javax.swing.JRadioButton Jrbtnpuesto48;
    private javax.swing.JRadioButton Jrbtnpuesto49;
    private javax.swing.JRadioButton Jrbtnpuesto5;
    private javax.swing.JRadioButton Jrbtnpuesto50;
    private javax.swing.JRadioButton Jrbtnpuesto51;
    private javax.swing.JRadioButton Jrbtnpuesto52;
    private javax.swing.JRadioButton Jrbtnpuesto53;
    private javax.swing.JRadioButton Jrbtnpuesto54;
    private javax.swing.JRadioButton Jrbtnpuesto55;
    private javax.swing.JRadioButton Jrbtnpuesto56;
    private javax.swing.JRadioButton Jrbtnpuesto57;
    private javax.swing.JRadioButton Jrbtnpuesto58;
    private javax.swing.JRadioButton Jrbtnpuesto59;
    private javax.swing.JRadioButton Jrbtnpuesto6;
    private javax.swing.JRadioButton Jrbtnpuesto60;
    private javax.swing.JRadioButton Jrbtnpuesto7;
    private javax.swing.JRadioButton Jrbtnpuesto8;
    private javax.swing.JRadioButton Jrbtnpuesto9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
